name: Linux Build

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust and target
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: i686-unknown-linux-gnu
        override: true

    - name: Install Linux cross-compilation dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y gcc-multilib
        sudo apt-get install -y g++-12-multilib
        sudo apt-get install -y libc6-dev-i386
        sudo apt-get install -y libstdc++-12-dev:i386
        sudo apt-get install -y libprotobuf-dev:i386 protobuf-compiler

    - name: Git Clone Dependencies
      run: |
        git clone https://github.com/alliedmodders/sourcemod --recursive -b 1.10-dev deps/sourcemod
        git clone https://github.com/alliedmodders/metamod-source -b 1.10-dev deps/mmsource
        git clone https://github.com/alliedmodders/hl2sdk -b csgo deps/hl2sdk-csgo

    - name: Build
      run: |
        export SOURCEMOD="${{ github.workspace }}/deps/sourcemod"
        export MMSOURCE="${{ github.workspace }}/deps/mmsource"
        export HL2SDKCSGO="${{ github.workspace }}/deps/hl2sdk-csgo"
        rustup target add i686-unknown-linux-gnu
        cargo build --target i686-unknown-linux-gnu --release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux
        path: target/i686-unknown-linux-gnu/release/